### ISSUE TITLE
timebox twitter results

### ISSUE THREAD

**Issue by eads** [nprapps/linklater#29]
Twitter doesn't let you search by date, but Tweet IDs are in some way sequential and can be used to determine time cut-offs.

**Comment by eads** [comment]
I don't know that we need to be precise and store the ID / datetime combos, but simply iterate back until a certain start date.

**Comment by suymilk** [comment]
I ended up not storing ID/datetime combos. There's minimal difference in execution time between when we call 30 and 200 (maximum) tweets at once to iterate over (but you should check my work), so I'm just breaking out of the for loop when the tweet's 'created_at' time stamp is older than the desired time frame. We can mark as closed once you've reviewed.

**Comment by suymilk** [comment]
@eads

**Comment by suymilk** [comment]
Github is being funky. @eads look at https://github.com/nprapps/linklater/commit/25a64209b3657d4a9b26867ccb4e2e8934b48522 to see if while loop implementation is correct?
